version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/main.sql:/docker-entrypoint-initdb.d/main.sql

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "5001:5001"
    depends_on:
      - postgres

  blog-service:
    build: ./blog-service
    container_name: blog-service
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "5002:5002"
    depends_on:
      - postgres

  comment-service:
    build: ./comment-service
    container_name: comment-service
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "5003:5003"
    depends_on:
      - postgres

volumes:
  postgres_data:
